### PR TITLE
Merge gocarina:master

### PR DESCRIPTION
**Pull request by siddharth178**
We need MarshalWithoutHeaders in MRI file processing available in master.

### CODE REVIEW

**Comment by siddharth178** [comment]
@andrei-m @jamesgarfield Can you please take a look?

**Comment by hchang-clypd** [comment]
@siddharth178 this was a little hard to read through, could you also share what you did to craft this PR?

**Comment by siddharth178** [comment]
@hchang-clypd Here is what I did

- clone clyphub/gocsv (origin)
- add remote gocarina/gocsv (upstream)
- fetch latest from gocarina/gocsv
- create a branch named MergeUpstream-for-MarshalWithoutHeaders
- do git merge upstream/master and resolve 1 conflict
- push my branch to origin
- raise a PR against origin/master

**Comment by hchang-clypd** [comment]
got it. thanks!

**Review by hchang-clypd — APPROVED** [review]

**Review by andrei-m — APPROVED** [review]
Looks reasonable :+1: 

Once you update the vendored version in our project, please be careful in following up on any unit or integration tests that may break from upstream changes.

**Comment by siddharth178** [comment]
@andrei-m sure!

**Pull request merged**
