### PR TITLE
Support aligning duplicate CSV row headers with the matching duplicate

### PR DESCRIPTION
**Pull request by BenjaminTrapani**
struct field header in the destination struct definition and test. Needed for https://clypdinc.atlassian.net/browse/MAIN-18165

### CODE REVIEW

**Comment by hchang-clypd** [comment]
so i do have a lot of concerns with this pull-request, as voiced earlier.  a couple of things i want to call out about this proposed change:
- yet another global var is not great.  gocsv uses it liberally, so maybe it is OK.  However, there's still concerns about global state that makes debugging/testing a challenge
- the logic here is brittle in that it assumes stable field ordering within the structdef.  more an annoyance than anything, I suppose, but I don't think it a super solid assumption to rely on
- given that this is meant to address a temporary failing, i dont think it worth to introduce this change now (especially in an upstream vendor package, even if we do have ownership of it) and rip it out later.  i think it less hassle to either "introduce an awk script to be run daily to pre-process the received files" or some other similar solution (probably can even do this in go), or even just manually 'fix' these files.  not elegant or anything, but definitely a preferred solution

**Comment by BenjaminTrapani** [comment]
@hchang-clypd Would you recommend that we introduce a preprocessing step before our ingesters to allow us to plug in correction logic to accommodate strange CSV formats in the future? If so, let's budget for developing this and block MAIN-18165 on its completion.

Edit: grammar

**Comment by hchang-clypd** [comment]
@BenjaminTrapani most definitely preprocessing preferred over patching here.  mind writing up the ticket?

**Comment by BenjaminTrapani** [comment]
@andrei-m Here is the pull request discussed in standup.

**Comment by andrei-m** [comment]
@BenjaminTrapani @hchang-clypd I agree that pre-processing the Discovery CSV to discard the specific duplicate column ahead of feeding it into gocsv seems better. This is hopefully not a use case we need to support often enough to warrant library support. The global flag also means that the same binary can only reliably support CSV parsing in one of the modes. In the 'on' state, this could mean that an error that we might want to be alerted and follow up with a data partner about would just be accepted.

The new story and blocking MAIN-18165 sounds good to me.

**Pull request closed without merging**
